services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=payments'
      - 'POSTGRES_PASSWORD=payments'
      - 'POSTGRES_USER=payments'
    ports:
      - '5433:5432'
