spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payments
    username: payments
    password: payments

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate